package com.m4g.timers;

public enum MissedScheduledPolicy{
	IGNORE,
	EXECUTE_NOW_ONCE,
	EXECUTE_NOW_WITH_EXISITING_COUNT,
	EXECUTE_NOW_WITH_REMAINING_COUNT,
	EXECUTE_NEXT_WITH_EXISITING_COUNT,
	EXECUTE_NEXT_WITH_REMAINING_COUNT;	
}
